In [233]:
# so here i am going to apply the NLP project just for the emotional sentiment analysis on the samll dataset

In [234]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [235]:
# so here i am using the emotion sentiment analysis file for the test with name of the train.txt

# hence the data is given and later it is surrounded by the ; in the text file

df=pd.read_csv('C:/Users/Acer/Emotional Analysis/train.txt',sep=';',header=None,names=['text','emotion'])

In [236]:
df.head(10)

                                                text   emotion
0                            i didnt feel humiliated   sadness
1  i can go from feeling so hopeless to so damned...   sadness
2   im grabbing a minute to post i feel greedy wrong     anger
3  i am ever feeling nostalgic about the fireplac...      love
4                               i am feeling grouchy     anger
5  ive been feeling a little burdened lately wasn...   sadness
6  ive been taking or milligrams or times recomme...  surprise
7  i feel as confused about life as a teenager or...      fear
8  i have been with petronas for years i feel tha...       joy
9                                i feel romantic too      love

In [237]:
# the data is going to contain the text and the emotion in the data
#in the two seperate number of the columns 

#now we have to check that it contains any of the null values 

df.isnull().sum()

text       0
emotion    0
dtype: int64

In [238]:
#so there is no null values in the data set

df['emotion'].unique()

<ArrowStringArray>
['sadness', 'anger', 'love', 'surprise', 'fear', 'joy']
Length: 6, dtype: str

In [239]:
unique_emotions=df['emotion'].unique()

emotion_numbers={}
i=0
for emo in unique_emotions:
    emotion_numbers[emo]=i
    i+=1
df['emotion']=df['emotion'].map(emotion_numbers)

In [240]:
df.dtypes

text         str
emotion    int64
dtype: object

In [241]:
#so in this we have converted our output variable into the numbers

df['text']=df['text'].apply(lambda x : x.lower())

#convert all the letters into the small letters

In [242]:
#Removing the punctuation in the text dataset 

import string

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [243]:
df['text']=df['text'].apply(remove_punc)
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [244]:
#removing the number in the text data sets 

def remove_numbers(txt):
    new=""
    for i in txt:
        if not i.isdigit():
            new=new+i
    return new

df['text']=df['text'].apply(remove_numbers)

In [245]:
#this is the function for removing any kind of the url using the regex

import re

def remove_urls(txt):
    pattern = r'https?://\S+|www\.\S+|\b[a-zA-Z0-9.-]+\.(com|org|net|edu|gov|io|co|in|uk|ai|me|info|biz)(/\S*)?\b'
    txt = re.sub(pattern, '', txt)
    return " ".join(txt.split())  # Remove extra spaces

df['text'] = df['text'].apply(remove_urls)

In [246]:
# for removing the html tags in our text dataset

import re

def remove_html_tags(txt):
    pattern = r'<.*?>'
    txt = re.sub(pattern, '', txt)
    return txt.strip()

df['text'] = df['text'].apply(remove_html_tags)

In [247]:
#for removing the emojis from the text dataset

import re

df["text"] = df["text"].apply(
    lambda x: re.sub(
        r'[\U0001F600-\U0001F64F'
        r'\U0001F300-\U0001F5FF'
        r'\U0001F680-\U0001F6FF'
        r'\U0001F1E0-\U0001F1FF'
        r'\U00002700-\U000027BF'
        r'\U000024C2-\U0001F251]+',
        '',
        x
    )
)

In [248]:
#in the machine learning context we have to remove the Stopwords like is , the ,was,etc

import nltk

In [249]:
from nltk.corpus import stopwords

from nltk.tokenize import word_tokenize

In [250]:
#now we are going to download all the punkt and the stopwords in this

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [251]:
#now after downloading all the stopwords

stop_words=set(stopwords.words('english'))
len(stop_words)

198

In [252]:
#now we get all the stopwords now i have to remove all the stopwords

df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [253]:
#so function for removing the stopwords

def remove(txt):
    words=word_tokenize(txt)
    cleaned=[]
    for i in words:
        if not i in stop_words:
            cleaned.append(i)
    return ' '.join(cleaned)

In [254]:
df['text']=df['text'].apply(remove)

In [255]:
df.loc[1]['text']

#so here we can see that all the bug words get removed all the data of the nlp is clean

'go feeling hopeless damned hopeful around someone cares awake'

In [256]:
df.head(20)

                                                 text  emotion
0                               didnt feel humiliated        0
1   go feeling hopeless damned hopeful around some...        0
2           im grabbing minute post feel greedy wrong        1
3   ever feeling nostalgic fireplace know still pr...        2
4                                     feeling grouchy        1
5       ive feeling little burdened lately wasnt sure        0
6   ive taking milligrams times recommended amount...        3
7      feel confused life teenager jaded year old man        4
8   petronas years feel petronas performed well ma...        5
9                                       feel romantic        2
10     feel like make suffering seeing mean something        0
11  feel running divine experience expect type spi...        5
12          think easiest time year feel dissatisfied        1
13                            feel low energy thirsty        0
14  immense sympathy general point possible proto ...        5
15                        feel reassured anxiety side        5
16                      didnt really feel embarrassed        0
17                          feel pretty pathetic time        0
18  started feeling sentimental dolls child began ...        0
19  feel compromised skeptical value every unit wo...        4

In [257]:
from sklearn.model_selection import train_test_split
X=df['text']
y=df['emotion']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [258]:
#now for the evaluation of the text data we are going to use the multinomial naive bayes model

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

bag_vectorizer=CountVectorizer()

X_train_bow=bag_vectorizer.fit_transform(X_train)
X_test_bow=bag_vectorizer.transform(X_test)

bow_nb=MultinomialNB()

bow_nb.fit(X_train_bow,y_train)

MultinomialNB()

In [259]:
y_pred_nb=bow_nb.predict(X_test_bow)
accuracy_score(y_test,y_pred_nb)

0.7678125

In [260]:
#now by using the Logistic regression 

from sklearn.linear_model import LogisticRegression

log_vectorizer=LogisticRegression(max_iter=1000)

log_vectorizer.fit(X_train_bow,y_train)

LogisticRegression(max_iter=1000)

In [261]:
y_pred_log=log_vectorizer.predict(X_test_bow)
accuracy_score(y_test,y_pred_log)

#so here the accuracy using the bow and the logistic regression is 88.87

0.88875

In [262]:
#now by using the svc for the classification problem 

from sklearn.svm import LinearSVC

svm_vectorizer=LinearSVC(random_state=42)
svm_vectorizer.fit(X_train_bow,y_train)

LinearSVC(random_state=42)

In [263]:
y_pred_svc=svm_vectorizer.predict(X_test_bow)
accuracy_score(y_test,y_pred_svc)

#so here the accuracy score is 88.96 using the svc

0.8896875

In [264]:
#now i am going to apply each of the technique and create the better model using the tf idf method

tf_vectorizer=TfidfVectorizer()

X_train_tf=tf_vectorizer.fit_transform(X_train)
X_test_tf=tf_vectorizer.transform(X_test)

In [265]:
#so lets test with the naive bayes 

tf_nb=MultinomialNB()
tf_nb.fit(X_train_tf,y_train)

MultinomialNB()

In [266]:
y_pred_tf_nb=tf_nb.predict(X_test_tf)
accuracy_score(y_test,y_pred_tf_nb)

#so it is 66.09

0.6609375

In [267]:
#now for the logistic regression 

log_tf=LogisticRegression(max_iter=1000)
log_tf.fit(X_train_tf,y_train)

y_pred_tf_log=log_tf.predict(X_test_tf)
accuracy_score(y_test,y_pred_tf_log)

#so this is around 86.15

0.8615625

In [268]:
svm_tf=LinearSVC(random_state=42)
svm_tf.fit(X_train_tf,y_train)

y_pred_tf_svm=svm_tf.predict(X_test_tf)
accuracy_score(y_test,y_pred_tf_svm)

#so it is 89.18

0.891875

In [269]:
#the best model we get is LinearSVC + TfIDFVectorizer

In [270]:
import joblib

joblib.dump(svm_tf, "model.joblib")
joblib.dump(tf_vectorizer, "vectorizer.joblib")

['vectorizer.joblib']

In [274]:
text = ["He seem helpless."]

text_vector = tf_vectorizer.transform(text)

prediction = svm_tf.predict(text_vector)

print(prediction)

[0]